name: "Composite Action testing Input and Output"
description: "This action will write out inputs and send back som outputs"


inputs:
  input_var:
    description: "This is the input variable"
outputs:
  output_var:
    description: "This is the output variable"
    value: ${{ steps.set-output-var.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Print out the input_var
      run: echo "The input is = ${{ inputs.input_var }}"
      shell: bash
    - name: Set output variable
      id: set-output-var
      ## run: echo "::set-output name=value::MyOutputValue" ## Deprecated way of setting output
      run: echo "value=MyOutputValue" >> $GITHUB_OUTPUT
      shell: bash
      